name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 0" 
  workflow_dispatch:      

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade yt-dlp pyinstaller -r requirements.txt

    - name: Download ffmpeg
      run: |
        curl -L -o ffmpeg.zip https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
        tar -xf ffmpeg.zip
        move ffmpeg-*/bin/ffmpeg.exe .

    - name: Build EXE
      run: pyinstaller --onefile --console --add-binary "ffmpeg.exe;." main.py

    - name: Publish/Update Single Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        git tag -f latest
        git push -f origin latest
        
        gh release create latest dist/main.exe --title "Latest Release" --notes "Автоматически обновляемая сборка с последними версиями yt-dlp и ffmpeg." --clobber || gh release upload latest dist/main.exe --clobber